Move set -e around to allow failures on not found

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -57,7 +57,7 @@ runs:
     run: |
       set -e
       set -u
-      set +o pipefail
+      set -o pipefail
 
       cd "${GITHUB_WORKSPACE}" || exit 1
 
@@ -113,8 +113,11 @@ runs:
       MODIFIED=
       echo "${INCLUDED}" | tr ' ' '\n' | while read INC; do
         if [ -n "${INC}" ]; then
+          # Allow failures when we can't find anything.
+          set +e
           MATCH=$(echo "${DIFFS}" | grep "${INC}")
           if [ $? -eq 0 ]; then
+            set -e
             if [ "${{ inputs.debug }}" = 'true' ]; then
               echo "::group:: Matched on pattern ${INC}."
               echo "$(echo "${MATCH}" | tr ' ' '\n')"
@@ -125,6 +128,7 @@ runs:
             MODIFIED=true
             break
           fi
+          set -e
         fi
       done
 
